# Numpy的使用

** 此系列的文件Udemy的python金融分析課程系列筆記(https://www.udemy.com/python-for-finance-and-trading-algorithms) **

** Numpy是一個pyhon做數值處理很強大的套件，本筆記介紹了簡單的使用 **

第一次使用的話需要簡單的使用!pip install numpy做安裝，而後import numpy引入套件

import之後可以將其取為新名稱np，後續的介紹也以np取代numpy

In [2]:
!pip install numpy

In [1]:
import numpy as np

首先試著使用list匯入np，將其轉為np的矩陣格式

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

我們也可以用類似python內建的range函數，只是在np裡面變為arange（array range）

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

np提供了迅速做零矩陣及一矩陣的方式如下

In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(3)

array([ 1.,  1.,  1.])

In [13]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

也可以給定一個初始值，最終值，及區間做矩陣

In [14]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [15]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

np內的單位矩陣做法如下

In [16]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

np提供了簡便的製作亂數函數

rand是隨機亂數，randn是符合常態分佈的亂數，randint則是取整數

如果想要固定亂數的話則可以使用random.seed做設定

In [17]:
np.random.rand(2)

array([ 0.77824827,  0.03745587])

In [18]:
np.random.rand(5,5)

array([[ 0.77531038,  0.16327663,  0.02338253,  0.88847151,  0.96085573],
       [ 0.54106332,  0.41658068,  0.72619275,  0.13483345,  0.77162674],
       [ 0.92928885,  0.0392944 ,  0.72244421,  0.87422688,  0.06922238],
       [ 0.88020992,  0.43345593,  0.59868769,  0.42047162,  0.03080926],
       [ 0.18918129,  0.7331605 ,  0.51897974,  0.97021589,  0.253106  ]])

In [19]:
np.random.randn(2)

array([-0.57039575, -0.04945516])

In [20]:
np.random.randn(5,5)

array([[ 0.13300581,  2.09956403, -2.02127327,  0.32283033, -1.50881828],
       [ 0.34461462,  1.85717058,  1.52777746, -0.98246134, -0.53621326],
       [ 1.63302158,  0.4284546 , -0.64297115, -0.99287232,  0.21348957],
       [-0.01048906,  0.06268012, -0.67984989,  1.43224035, -2.26277144],
       [-1.20534375,  0.41734023,  1.07273734,  0.53647202,  0.71884833]])

In [21]:
np.random.randint(1,100)

83

In [22]:
np.random.randint(1,100,10)

array([69, 31,  4, 18, 85, 24, 59,  8, 83, 20])

上面這些做法都可以指定給某個變數

並且可以對他做重新排列（重新排列成幾乘幾的矩陣，必須注意內部的值的數量相同與否）

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr = np.arange(25)
arr.reshape(4,5) # 這邊數量不對就會無法重新排列

ValueError: cannot reshape array of size 25 into shape (4,5)

簡單的方法找出矩陣內的最大最小值，也可以找出對應的位置

In [26]:
ranarr

array([41, 17, 35, 35, 38, 48,  5,  3,  5,  6])

In [27]:
ranarr.max()

48

In [28]:
ranarr.argmax()

5

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.reshape(5,5).max()

24

shape方法是查看矩陣的形狀

dtype是查看內涵的值的格式

In [37]:
arr.shape

(25,)

In [38]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
arr.reshape(1,25).shape

(1, 25)

In [40]:
arr.dtype

dtype('int64')

np的矩陣也可以用類似list的方法去做索引查找

也可以利用索引值做內部值得改寫

可以取出矩陣的部分值給其他變數，但要注意改動的時候原矩陣也會改動

In [53]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8]

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [58]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

有行根列的矩陣（二維矩陣），可以把它想成陣列包陣列

一樣可以利用list同樣的邏輯做索引，另外就是np矩陣的索引可以給行跟列一起包在一個中括號內部

[:2,1:]表示要從第0 row到第2 row（不包含2），並且從1column到最後

In [61]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[1]

array([20, 25, 30])

In [63]:
arr_2d[1][0]

20

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

另外一個方便的事情是，可以在矩陣內做條件判斷搜尋

結果會返回一個布林矩陣，並且可以用它當作索引去得到需要的矩陣內值

In [70]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [72]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr = arr.reshape(2,5)

In [79]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [80]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

np矩陣也可以簡單的做一些數學運算如下

In [81]:
arr = np.arange(0,10)

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [83]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [84]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [85]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])